---

- name: ensure packages are installed
  pip:
    name: prometheus-pgbouncer-exporter
    version: "{{ pgbouncer_exporter_version }}"
    executable: pip3
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: create system group
  group:
    name: "{{ pgbouncer_exporter_group }}"
    state: present

- name: create system user
  user:
    name: "{{ pgbouncer_exporter_user }}"
    createhome: false
