---

- name: Converge
  hosts: all
  connection: local

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.pip
      pip_package: python36-pip
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.pip
      pip_package: python3-pip
      when: ansible_os_family == 'Debian'
    - role: ansible-role-prometheus-pgbouncer-exporter
